import type { SentimentDisplay } from '@/types';

/** Per-category keyword lists used for sentiment classification of articles */
export const SENTIMENT_KEYWORDS: Record<string, { positive: string[]; negative: string[] }> = {
  vd: {
    positive: [
      'koopkans',
      'kopen',
      'bull',
      'stijgt',
      'groei',
      'winst',
      'positief',
      'opwaarts',
      'record',
      'buy',
      'upside',
      'gains',
    ],
    negative: ['verkopen', 'bear', 'daalt', 'crash', 'risico', 'verlies', 'negatief', 'sell', 'downside', 'crisis'],
  },
  to: {
    positive: [
      'lng',
      'record',
      'dividend',
      'special dividend',
      'growth',
      'production',
      'rises',
      'surges',
      'higher',
      'strong',
      'beats',
      'profit',
      'gains',
      'rallies',
      'henry hub',
      'contract',
      'aeco recovers',
      'aeco rises',
      'aeco higher',
      'lng canada phase',
      'phase 2 approved',
      'phase 2 confirmed',
      'buyback',
      'data center demand',
      'cash flow',
      'free cash flow',
    ],
    negative: [
      'cut',
      'decline',
      'miss',
      'lower',
      'weak',
      'delay',
      'loss',
      'oversupply',
      'slump',
      'drop',
      'fall',
      'crash',
      'verlies',
      'warm weather',
      'pipeline delay',
      'pipeline cancel',
      'regulatory',
      'carbon tax',
      'aeco falls',
      'aeco drops',
      'aeco lower',
    ],
  },
  iv: {
    positive: [
      'copper price rises',
      'copper rises',
      'copper surges',
      'copper demand',
      'copper deficit',
      'record',
      'expansion',
      'production',
      'demand',
      'growth',
      'strong',
      'upgrade',
      'profit',
      'green energy',
      'ev',
      'ai demand',
      'ai copper',
      'electrification',
      'gains',
      'rally',
      'smelter',
      'blister',
    ],
    negative: [
      'unrest',
      'conflict',
      'war',
      'flood',
      'power outage',
      'cut',
      'decline',
      'lower',
      'copper falls',
      'copper drops',
      'copper slumps',
      'copper surplus',
      'copper oversupply',
      'miss',
      'delay',
      'sanction',
      'drops',
      'surplus',
      'political instability',
      'instability',
      'coup',
      'militia',
      'drc conflict',
      'congo conflict',
      'capex overrun',
    ],
  },
  ts: {
    positive: [
      'record',
      'ai demand',
      'growth',
      'revenue',
      'strong',
      'beats',
      'expansion',
      'chips',
      'profit',
      'upgrade',
      'rallies',
      'gains',
    ],
    negative: [
      'tension',
      'military',
      'war',
      'invasion',
      'blockade',
      'sanctions',
      'conflict',
      'threat',
      'escalat',
      'drops',
      'falls',
      'miss',
    ],
  },
  ct: {
    positive: [
      'pause',
      'hold',
      'no hike',
      'yen weakens',
      'yen falls',
      'stable',
      'dovish',
      'eases',
      'rate cut',
      'fundamentals intact',
      'buying opportunity',
      'koopkans',
      'bijkopen',
    ],
    negative: [
      'hike',
      'rate hike',
      'raises rates',
      'yen surges',
      'yen strengthens',
      'unwind',
      'sell-off',
      'selloff',
      'crash',
      'margin call',
      'risk-off',
      'nikkei falls',
      'nikkei drops',
      'tech selloff',
      'liquidation',
      'boj raises',
      'nasdaq drops',
      'nasdaq falls',
      'tech stocks fall',
      'market correction',
      'marktcorrectie',
    ],
  },
};

/** Display styles and labels for each sentiment level */
export const SENTIMENT_DISPLAY: Record<string, SentimentDisplay> = {
  positive: { backgroundClass: 'bp', arrowClass: 'ap', pillClass: 'pp', icon: '↑', label: 'Positief' },
  negative: { backgroundClass: 'bn', arrowClass: 'an', pillClass: 'pn', icon: '↓', label: 'Negatief' },
  neutral: { backgroundClass: 'bu', arrowClass: 'au', pillClass: 'pu', icon: '→', label: 'Neutraal' },
};
